`timescale 1ns/1ps

module gc_lut_512 #(
    parameter GLOBAL_ADDR_WIDTH = 12, // 12 bits for 4096 addresses
    parameter LUT_SIZE = 512,         // Number of bad addresses to store
    parameter SRAM_ADDR_WIDTH = 9     // 9 bits to address 512 SRAM lines (log2(512))
)(
    input  wire [GLOBAL_ADDR_WIDTH-1:0] global_addr,  // Address requested by CPU
    
    output reg                          hit,          // 1 if address is bad (in LUT), 0 if good
    output reg  [SRAM_ADDR_WIDTH-1:0]   sram_addr     // The translated index for the SRAM
);

    // Array to store the 512 bad addresses (12 bits each)
    reg [GLOBAL_ADDR_WIDTH-1:0] bad_addr_array [0:LUT_SIZE-1];

    // Load the bad addresses generated by our Python script
    initial begin
        $readmemh("../DRT_ARRAYS/bad_addresses_4096.mem", bad_addr_array);
    end

    // --- Fully Associative Search Logic ---
    // This combinational block searches for the global_addr inside the array
    integer i;
    always @(*) begin
        hit = 1'b0;                           // Default: Not found
        sram_addr = {SRAM_ADDR_WIDTH{1'b0}};  // Default index

        // Search through all 512 entries
        for (i = 0; i < LUT_SIZE; i = i + 1) begin
            if (bad_addr_array[i] == global_addr) begin
                hit = 1'b1;       // Match found!
                sram_addr = i;    // Output the internal index for the SRAM
            end
        end
    end

endmodule